repos:
  - repo: local
    hooks:

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]

      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]

#      - id: coverage
#        name: Coverage
#        entry: coverage run --source=. -m unittest
#        language: system
#        pass_filenames: false
#        always_run: true
#        verbose: true

      - id: radon-cc
        name: Radon CC
        entry: radon cc . -se '*/tests/*' --order SCORE -a # > radon.cyclomatic-complexity.txt
        language: system
        pass_filenames: false
        always_run: false

      - id: radon-mi
        name: Radon MI
        entry: radon mi . -se '*/tests/*' --sort # > radon.maintainability-index.txt
        language: system
        pass_filenames: false
        always_run: false

      #      - id: radon-raw
      #        name: Radon RAW
      #        entry: radon raw . -s # > radon.raw.txt
      #        language: system
      #        pass_filenames: false
      #        always_run: false
      #        verbose: true

      - id: radon-hal
        name: Radon Halstead
        entry: radon hal . # > radon.Halstead.txt
        language: system
        pass_filenames: false
        always_run: false

      - id: generate-docs-md
        name: Generate Docs
        entry: uv run scripts/analyze.py
        language: system
        pass_filenames: false
        always_run: true