repos:
  - repo: local
    hooks:

      - id: ruff-check
        name: ruff check
        entry: ruff check
        language: system
        types: [ python ]

      - id: ruff-fix
        name: ruff fix
        entry: ruff check
        language: system
        types: [ python ]
        args: [ --fix, --exit-non-zero-on-fix ]

      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [ python ]

      #      - id: pylint
      #        name: pylint
      #        entry: uv run pylint
      #        language: system
      #        types: [ python ]

      #      - id: coverage
      #        name: Coverage
      #        entry: coverage run --source=. -m unittest
      #        language: system
      #        pass_filenames: false
      #        always_run: true
      #        verbose: true

      - id: radon-cc
        name: Radon CC
        entry: radon cc . -se '*/tests/*' --order SCORE -a # > radon.cyclomatic-complexity.txt
        language: system
        pass_filenames: false
        always_run: false

      - id: radon-mi
        name: Radon MI
        entry: radon mi . -se '*/tests/*' --sort # > radon.maintainability-index.txt
        language: system
        pass_filenames: false
        always_run: false

      #      - id: radon-raw
      #        name: Radon RAW
      #        entry: radon raw . -s # > radon.raw.txt
      #        language: system
      #        pass_filenames: false
      #        always_run: false
      #        verbose: true

      - id: radon-hal
        name: Radon Halstead
        entry: radon hal . # > radon.Halstead.txt
        language: system
        pass_filenames: false
        always_run: false
