[project]
name = "data-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
aa-common = { workspace = true }

data-file-ingestion = { workspace = true }
data-file-repository = { workspace = true }
data-file-repository-pg = { workspace = true }

file-repository = { workspace = true }
file-repository-posix = { workspace = true }
file-repository-s3 = { workspace = true }

measure-io = { workspace = true }
measure-io-datafile = { workspace = true }
measure-io-influxdb = { workspace = true }
measure-io-kafka = { workspace = true }
measure-io-open-meteo = { workspace = true }

message-queue = { workspace = true }
message-queue-kafka = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
