[project]
name = "data-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
measure-repository = { workspace = true }
measure-open-meteo = { workspace = true }
broker-api = { workspace = true }
broker-kafka = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
