[project]
name = "data-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cfgrib>=0.9.15.0",
    "fastapi>=0.115.12",
    "python-multipart>=0.0.20",
    "scipy>=1.15.2",
    "uvicorn>=0.34.2",
]

[tool.uv.workspace]
members = [
    "projects/*",
    "adapters/*"
]

[tool.uv.sources]
aa-common = { workspace = true }

meteo-measures = { workspace = true }

message-queue = { workspace = true }
message-queue-kafka = { workspace = true }

data-file-repository = { workspace = true }
data-file-repository-pg = { workspace = true }

file-repository = { workspace = true }
file-repository-posix = { workspace = true }
file-repository-s3 = { workspace = true }

measure-repository = { workspace = true }
measure-repository-datafile = { workspace = true }
measure-repository-influxdb = { workspace = true }
measure-repository-openmeteo = { workspace = true }

[tool.isort]
profile = "black"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "coverage>=7.8.0",
    "flake8>=7.2.0",
    "isort>=6.0.1",
    "pre-commit>=4.2.0",
    "radon>=6.0.1",
]
