[project]
name = "data-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.5.2",
]

[tool.uv.workspace]
members = [
    "projects/*",
    "adapters/*",
    "connectors/*",
]

[tool.uv.sources]
aa-common = { workspace = true }

meteo-domain = { workspace = true }
meteo-app = { workspace = true }

message-queue = { workspace = true }
message-queue-kafka = { workspace = true }

data-file-repository = { workspace = true }
data-file-repository-pg = { workspace = true }

file-repository = { workspace = true }
file-repository-posix = { workspace = true }
file-repository-s3 = { workspace = true }

measure-repository = { workspace = true }
measure-repository-datafile = { workspace = true }
measure-repository-influxdb = { workspace = true }
measure-repository-openmeteo = { workspace = true }

# connectors
pg-connector = { workspace = true }
influxdb-connector = { workspace = true }
s3-connector = { workspace = true }
kafka-connector = { workspace = true }

[tool.ruff]
# Règles à activer
lint.select = ["E", "F", "B", "I", "N", "UP", "PL"]  # PL active les règles équivalentes à Pylint

# Ignore les erreurs d'importation pour les packages spécifiques
lint.extend-ignore = []

# Chemins à ignorer
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "C0116", # missing-function-docstring
    "c-extension-no-member",
]

[tool.pylint."DESIGN"]
min-public-methods = 1

[dependency-groups]
dev = [
    "black>=25.1.0",
    "coverage>=7.8.0",
    "flake8>=7.2.0",
    "isort>=6.0.1",
    "pdoc>=15.0.3",
    "pre-commit>=4.2.0",
    "pydeps>=3.0.1",
    "pylint>=3.3.6",
    "radon>=6.0.1",
    "ruff>=0.11.8",
]
