[project]
name = "data-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cfgrib>=0.9.15.0",
    "eccodes>=2.41.0",
    "fastapi>=0.115.12",
    "python-multipart>=0.0.20",
    "scipy>=1.15.2",
    "uvicorn>=0.34.2",
    "zarr>=3.0.7",
]

[tool.uv.sources]
aa-common = { workspace = true }

meteo-measures = { workspace = true }

message-queue = { workspace = true }
message-queue-kafka = { workspace = true }

data-file-repository = { workspace = true }
data-file-repository-pg = { workspace = true }

file-repository = { workspace = true }
file-repository-posix = { workspace = true }
file-repository-s3 = { workspace = true }

measure-repository = { workspace = true }
measure-repository-datafile = { workspace = true }
measure-repository-influxdb = { workspace = true }
measure-repository-openmeteo = { workspace = true }


[tool.uv.workspace]
members = [
    "common/*",
    "projects/*",
    "adapters/*"
]
