version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: meteo-db
    volumes:
      - postgres-data:/data/measures/postgresql

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: meteo-data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: server-token
    volumes:
      - influxdb-data:/var/lib/influxdb

volumes:
  influxdb-data:
  postgres-data:
